// State Management Engine
const state = {
    user: null,
    score: 100, // Starting point balance
    stage: 1,
    completedCount: 0,
    layout: 'card', // 'card' or 'split'
    records: [],
    currentPuzzle: null,
    selectedAuthAnswer: null
};

// Standard Mathematical Sequential Puzzle Engine
const MathEngine = {
    generatePuzzle(stage) {
        const puzzleTypes = ['ARITHMETIC_PROGRESSION', 'GEOMETRIC_RATIO', 'EXPONENTIAL_SEQUENCE', 'MISSING_OPERAND'];
        const type = puzzleTypes[Math.floor(Math.random() * puzzleTypes.length)];

        if (type === 'ARITHMETIC_PROGRESSION') {
            return this.generateArithmetic(stage);
        } else if (type === 'GEOMETRIC_RATIO') {
            return this.generateGeometric(stage);
        } else if (type === 'EXPONENTIAL_SEQUENCE') {
            return this.generateExponential(stage);
        } else {
            return this.generateMissingOperand(stage);
        }
    },

    generateArithmetic(stage) {
        const start = Math.floor(Math.random() * 10) + 2;
        const diff = Math.floor(Math.random() * 5) + 2 + Math.floor(stage / 3);
        const sequence = [start, start + diff, start + (diff * 2), start + (diff * 3)];
        const target = start + (diff * 4);

        const options = this.buildOptions(target);

        return {
            title: "Linear Arithmetic Progression",
            instruction: "Identify the next sequential value in the constant increment pathway.",
            sequenceDisplay: `${sequence.join(" → ")} → <span class="text-brand-red font-bold font-mono">?</span>`,
            options: options
        };
    },

    generateGeometric(stage) {
        const start = Math.floor(Math.random() * 4) + 2;
        const ratio = 2;
        const sequence = [start, start * ratio, start * (ratio ** 2), start * (ratio ** 3)];
        const target = start * (ratio ** 4);

        const options = this.buildOptions(target);

        return {
            title: "Geometric Multiplicative Sequence",
            instruction: "Calculate the subsequent term generated by the constant multiplier.",
            sequenceDisplay: `${sequence.join(" → ")} → <span class="text-brand-red font-bold font-mono">?</span>`,
            options: options
        };
    },

    generateExponential(stage) {
        const base = Math.floor(Math.random() * 3) + 1;
        const sequence = [1 ** 2 + base, 2 ** 2 + base, 3 ** 2 + base, 4 ** 2 + base];
        const target = 5 ** 2 + base;

        const options = this.buildOptions(target);

        return {
            title: "Exponential Square Sequence",
            instruction: "Evaluate the quadratic step progression to determine the final term.",
            sequenceDisplay: `${sequence.join(" → ")} → <span class="text-brand-red font-bold font-mono">?</span>`,
            options: options
        };
    },

    generateMissingOperand(stage) {
        const a = Math.floor(Math.random() * 12) + 5;
        const b = Math.floor(Math.random() * 8) + 2;
        const target = a * b;

        const options = this.buildOptions(b);

        return {
            title: "Equation Factor Completion",
            instruction: "Find the missing operand factor that fulfills the mathematical equivalence.",
            sequenceDisplay: `${a} × <span class="text-brand-red font-bold font-mono">?</span> = ${target}`,
            options: options
        };
    },

    buildOptions(correctValue) {
        const offsets = [-3, -1, 2, 4].sort(() => Math.random() - 0.5);
        const options = [
            { val: correctValue, isCorrect: true },
            { val: correctValue + offsets[0], isCorrect: false },
            { val: correctValue + offsets[1], isCorrect: false },
            { val: correctValue + offsets[2], isCorrect: false }
        ];
        return options.sort(() => Math.random() - 0.5);
    }
};

// Global Application Controller
const App = {
    init() {
        this.loadStorage();
        this.updateUI();
    },

    loadStorage() {
        const saved = localStorage.getItem('nexus_math_soft_ui');
        if (saved) {
            try {
                const parsed = JSON.parse(saved);
                state.user = parsed.user;
                state.score = parsed.score ?? 100;
                state.stage = parsed.stage ?? 1;
                state.completedCount = parsed.completedCount ?? 0;
                state.records = parsed.records ?? [];
            } catch (e) {
                console.error("Storage Recovery Exception", e);
            }
        }
    },

    saveStorage() {
        localStorage.setItem('nexus_math_soft_ui', JSON.stringify({
            user: state.user,
            score: state.score,
            stage: state.stage,
            completedCount: state.completedCount,
            records: state.records
        }));
    },

    updateUI() {
        document.getElementById('global-score').textContent = `${state.score} PT`;
        if (state.user) {
            document.getElementById('nav-controls').classList.remove('hidden');
            document.getElementById('user-display').textContent = state.user;
        } else {
            document.getElementById('nav-controls').classList.add('hidden');
        }
    },

    navigate(view) {
        document.querySelectorAll("section[id^='view-']").forEach(el => el.classList.add('hidden'));
        document.getElementById(`view-${view}`).classList.remove('hidden');

        if (view === 'game') {
            this.renderPuzzle();
        } else if (view === 'records') {
            this.renderRecords();
        }
    },

    setLayout(type) {
        state.layout = type;
        document.getElementById('btn-layout-card').className = type === 'card' 
            ? 'px-3 py-1.5 rounded-md font-semibold bg-white text-slate-800 shadow-sm transition' 
            : 'px-3 py-1.5 rounded-md font-semibold text-slate-500 hover:text-slate-800 transition';
        document.getElementById('btn-layout-split').className = type === 'split' 
            ? 'px-3 py-1.5 rounded-md font-semibold bg-white text-slate-800 shadow-sm transition' 
            : 'px-3 py-1.5 rounded-md font-semibold text-slate-500 hover:text-slate-800 transition';
        
        if (!document.getElementById('view-game').classList.contains('hidden')) {
            this.renderPuzzle();
        }
    },

    renderPuzzle() {
        state.currentPuzzle = MathEngine.generatePuzzle(state.stage);
        const container = document.getElementById('game-layout-container');
        document.getElementById('level-display-title').textContent = `Stage ${state.stage}`;
        
        const p = state.currentPuzzle;

        if (state.layout === 'card') {
            container.innerHTML = `
                <div class="bg-white border border-slate-200/80 rounded-2xl p-8 max-w-xl mx-auto w-full shadow-xl shadow-slate-200/50">
                    <div class="flex items-center gap-2 mb-2">
                        <i class="fa-solid fa-square-root-variable text-brand-red text-xs"></i>
                        <span class="text-xs font-mono font-bold text-brand-red uppercase">${p.title}</span>
                    </div>
                    <p class="text-xs text-slate-500 font-medium mb-6">${p.instruction}</p>

                    <div class="bg-slate-50 border border-slate-200/60 rounded-xl p-6 text-center text-xl md:text-2xl font-mono text-slate-800 mb-8 shadow-inner">
                        ${p.sequenceDisplay}
                    </div>

                    <div class="grid grid-cols-2 gap-3 font-mono">
                        ${p.options.map((opt, idx) => `
                            <button onclick="App.evaluateAnswer(${opt.isCorrect})" class="p-4 bg-white border border-slate-200 hover:border-brand-red hover:bg-red-50/30 rounded-xl flex items-center justify-center gap-3 transition font-semibold text-slate-800 shadow-sm group">
                                <span class="text-xs font-bold text-brand-red group-hover:text-red-700">${String.fromCharCode(65 + idx)})</span>
                                <span class="text-base">${opt.val}</span>
                            </button>
                        `).join('')}
                    </div>
                </div>
            `;
        } else {
            container.innerHTML = `
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6 w-full">
                    <div class="bg-white border border-slate-200/80 rounded-2xl p-8 shadow-xl shadow-slate-200/50 flex flex-col justify-between">
                        <div>
                            <div class="flex items-center gap-2 mb-2">
                                <i class="fa-solid fa-square-root-variable text-brand-red text-xs"></i>
                                <span class="text-xs font-mono font-bold text-brand-red uppercase">${p.title}</span>
                            </div>
                            <p class="text-xs text-slate-500 font-medium mb-6">${p.instruction}</p>
                        </div>
                        <div class="bg-slate-50 border border-slate-200/60 rounded-xl p-8 text-center text-2xl font-mono text-slate-800 my-auto shadow-inner">
                            ${p.sequenceDisplay}
                        </div>
                    </div>

                    <div class="bg-white border border-slate-200/80 rounded-2xl p-8 shadow-xl shadow-slate-200/50 flex flex-col justify-center">
                        <span class="text-xs font-mono font-bold text-slate-400 mb-4 block uppercase">Select Solution Term:</span>
                        <div class="space-y-3 font-mono">
                            ${p.options.map((opt, idx) => `
                                <button onclick="App.evaluateAnswer(${opt.isCorrect})" class="w-full p-4 bg-white border border-slate-200 hover:border-brand-red hover:bg-red-50/30 rounded-xl flex items-center justify-between transition font-semibold text-slate-800 shadow-sm group">
                                    <span class="text-xs font-bold text-brand-red group-hover:text-red-700">Option ${String.fromCharCode(65 + idx)}</span>
                                    <span class="text-base">${opt.val}</span>
                                </button>
                            `).join('')}
                        </div>
                    </div>
                </div>
            `;
        }
    },

    evaluateAnswer(isCorrect) {
        if (isCorrect) {
            state.score += 20;
            state.stage += 1;
            state.completedCount += 1;

            this.logRecord(`Cleared Stage ${state.stage - 1}`, +20);
            this.saveStorage();
            this.updateUI();
            this.showModal('Correct Solution! +20 PT Earned', 'fa-circle-check');
            this.renderPuzzle();
        } else {
            this.deductPoints(10, 'Incorrect Answer');
        }
    },

    skipLevel() {
        this.deductPoints(10, 'Stage Skipped');
        if (state.score > 0) {
            state.stage += 1;
            this.saveStorage();
            this.updateUI();
            this.renderPuzzle();
        }
    },

    deductPoints(pts, reason) {
        state.score -= pts;

        if (state.score <= 0) {
            state.score = 0;
            this.logRecord(`Evaluation Knockout (${reason})`, -pts);
            this.saveStorage();
            this.updateUI();
            this.showModal('Knockout! Point Balance Exhausted. Stage Reset.', 'fa-skull');
            
            // Reset evaluation state
            state.score = 100;
            state.stage = 1;
            this.saveStorage();
            this.updateUI();
            this.renderPuzzle();
        } else {
            this.logRecord(`${reason}`, -pts);
            this.saveStorage();
            this.updateUI();
            this.showModal(`${reason}! -${pts} PT Deducted.`, 'fa-triangle-exclamation');
        }
    },

    logRecord(action, ptChange) {
        state.records.unshift({
            action: action,
            ptChange: ptChange,
            totalScore: state.score,
            timestamp: new Date().toLocaleTimeString()
        });
    },

    renderRecords() {
        document.getElementById('record-score').textContent = `${state.score} PT`;
        document.getElementById('record-stage').textContent = `Stage ${state.stage}`;
        document.getElementById('record-count').textContent = state.completedCount;

        const list = document.getElementById('records-list');
        if (state.records.length === 0) {
            list.innerHTML = `<div class="p-4 text-center text-slate-400 font-semibold">No recorded activity logs available.</div>`;
            return;
        }

        list.innerHTML = state.records.map(r => `
            <div class="flex justify-between items-center p-3.5 bg-slate-50 border border-slate-200/80 rounded-xl">
                <span class="font-bold uppercase ${r.ptChange < 0 ? 'text-brand-red' : 'text-slate-800'}">${r.action}</span>
                <span class="font-bold ${r.ptChange < 0 ? 'text-brand-red' : 'text-emerald-600'}">${r.ptChange > 0 ? '+' : ''}${r.ptChange} PT</span>
                <span class="text-slate-400 text-[11px] font-semibold">${r.timestamp}</span>
            </div>
        `).join('');
    },

    showModal(msg, icon = 'fa-triangle-exclamation') {
        document.getElementById('modal-msg').textContent = msg;
        document.getElementById('modal-icon').innerHTML = `<i class="fa-solid ${icon}"></i>`;
        document.getElementById('custom-modal').classList.remove('hidden');
    },

    closeModal() {
        document.getElementById('custom-modal').classList.add('hidden');
    }
};

// Paginated Authentication Flow Controller
const Auth = {
    nextPage(pageNumber) {
        if (pageNumber === 2) {
            const name = document.getElementById('auth-username').value.trim();
            if (!name) {
                App.showModal('Please enter a candidate identifier');
                return;
            }
            state.user = name;
        }

        document.querySelectorAll('.auth-page').forEach(el => el.classList.add('hidden'));
        document.getElementById(`auth-page-${pageNumber}`).classList.remove('hidden');
        document.getElementById('auth-page-indicator').textContent = `Page ${pageNumber} of 2`;
    },

    selectAnswer(btn, option) {
        document.querySelectorAll('.auth-opt').forEach(el => el.classList.remove('border-brand-red', 'bg-red-50/50'));
        btn.classList.add('border-brand-red', 'bg-red-50/50');
        state.selectedAuthAnswer = option;
    },

    complete() {
        App.saveStorage();
        App.updateUI();
        App.navigate('game');
    },

    logout() {
        state.user = null;
        localStorage.removeItem('nexus_math_soft_ui');
        window.location.reload();
    }
};

// Application Bootstrapper
window.onload = () => {
    App.init();
    if (state.user) {
        App.navigate('game');
    } else {
        App.navigate('auth');
    }
};